### ISSUE TITLE
Reloading the Kernel/Config/Files/ZZZ*.pm files

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#1000]
Apparently the commit 7fb462d has fixed the issues with SecureMode.
However there are at least two concerns:

- [x]  Constantly reloading ZZZAAuto.pm is not elegant, not sure whether it is a noticable performance hit
- [x] There are other Kernel/Config/File/ZZZ*.pm files which must also reliably be reloaded. The lack of reloading might be related to TODO failure in the Selenium tests

So, lets close this issue and open a new issue for the improvements.

_Originally posted by @bschmalhofer in https://github.com/RotherOSS/otobo/issues/789#issuecomment-836685006_

**Comment by bschmalhofer** [comment]
Let's have a recap of the current state.

### A note about inodes

`Apache2::Reload` only looks at the modified time of files. This is a bit coarse, as it is based on seconds. `Module::Refresh` also takes the inode number into account. My understanding is that `Kernel::System::SysConfig::_FileWriteAtomic()` does change the inode number, which would make `Module::Refresh` based solutions more reliable.

### Running under Apache2/mod_perl

In the Apache config we have:

```
    # Reload Perl modules when changed on disk
    PerlModule Apache2::Reload
    PerlInitHandler Apache2::Reload
```
For every mod_perl request, the modules in %INC are reloaded at the start of the request . So when `Kernel::Config::Defaults::new()` calls the `Load()` method of a ZZZ-module, it is guaranteed that it get the version that existed when the request was started. This works, assuming that no 'same second' effects occurs.

### OTOBO 10.0.10 running under PSGI

`Plack::Middleware::Refresh` is run before the middleware `$RefreshZZZAAutoMiddleWare`. `Plack::Middleware::Refresh` uses `Module::Refresh` under the hood and only reloads changed modules every 10s. This is too long for tracking changes in the ZZZ-Modules. Therefore `$RefreshZZZAAutoMiddleWare` reloads  _Kernel/Config/Files/ZZZAAuto.pm_ for every request, without checking whether it was modified.

### The problem

TODO: not sure whether this is really the cause

1. Assuming a single process
2. otobo.psgi starts, `%Module::Refresh::Cache` is initialized but ZZZAAuto.pm is not yet in %INC, and therefore not in %CACHE
3. Kernel::Config::Defaults->new() is called, and ZZZAAuto,.pm is loaded
5. The SysConfig changes ZZZAuto.pm, but ZZZAuto still not in %CACHE 
6. next request: ZZZAAuto,pm is not reloaded because it is not in %CACHE, but now is added to %CACHE
7. Error because the Config is not up to date

### The solution

TODO: not sure whether this is really the solution

Put the ZZZ-Module into %Cache in `Kernel::Config::Defaults::new()`.

**Comment by bschmalhofer** [comment]
First test run looks fine. No new failures, but more TODO tests have passed. Let's check some more test runs in the next days.

**Comment by bschmalhofer** [comment]
This change should allow to unTODO some test cases. See the following issues:

- [x] https://github.com/RotherOSS/otobo/issues/763 : TODO tests are unTODOed, looks good
- [x] https://github.com/RotherOSS/otobo/issues/929 : failures are either fixed, or marked as TODO for #1002 
- [x] https://github.com/RotherOSS/otobo/issues/748  : does not work for NewOwnerID and State. but config setting seems to work
- [x] https://github.com/RotherOSS/otobo/issues/921 : fixed two errors in test suite, looks fine now

**Comment by bschmalhofer** [comment]
Looking at the implementation of `Kernel::System::UnitTest::ConfigSettingChange` I found that the order of written _ZZZZUnitTest*.pm_ is not deterministic. This is bad when the same setting is modified twice or more often in a test script. The written files should be in alphabetical order.

- [x] Saner naming convention for _ZZZZUnitTest*.pm_ files

**Comment by bschmalhofer** [comment]
Selenium tests are mostly fine in the rel-10_1 branch. Now let's check whether they succeed in rel-10_1 too.

**Comment by bschmalhofer** [comment]
There is another prolblem. The log output of the otobo_web_1 shows many messages like:

`[Sat May 22 16:24:09 2021] plackup: Can't locate Kernel/Config/Files/ZZZZUnitTestAB4400000059500001.pm in @INC (you may need to install the Kernel::Config::Files::ZZZZUnitTestAB4400000059500001 module) (@INC contains: /opt/otobo/bin/psgi-bin/../../Custom /opt/otobo/bin/psgi-bin/../../Kernel/cpan-lib /opt/otobo/bin/psgi-bin/../.. /opt/otobo_install/local/lib/perl5/5.32.0/x86_64-linux-gnu /opt/otobo_install/local/lib/perl5/5.32.0 /opt/otobo_install/local/lib/perl5/x86_64-linux-gnu /opt/otobo_install/local/lib/perl5 /opt/otobo/local/lib/perl5 /usr/local/lib/perl5/site_perl/5.32.0/x86_64-linux-gnu /usr/local/lib/perl5/site_perl/5.32.0 /usr/local/lib/perl5/vendor_perl/5.32.0/x86_64-linux-gnu /usr/local/lib/perl5/vendor_perl/5.32.0 /usr/local/lib/perl5/5.32.0/x86_64-linux-gnu /usr/local/lib/perl5/5.32.0) at /opt/otobo/bin/psgi-bin/../../Kernel/cpan-lib/Module/Refresh.pm line 121. `

The cause is obvious. The  _Kernel/Config/Files/ZZZZUnitTest*.pm_ files are created by an instance of `Kernel::System::UnitTest::Helper` and are removed again when that instance is destroyed. However the loaded modules are still in `%INC` and `Module::Refresh` still try to determine whether they should be reloaded. The good news is that this check is not needed at all, as `Kernel::Config::Defaults::new()` handles these files separately. But how can that be done?

**Comment by bschmalhofer** [comment]
Replaced Plack::Middleware::Refresh with a custom middleware in order to have more control. The warnings are gone and the unit tests look fine again.

**Comment by bschmalhofer** [comment]
Tests look fine. Closing this issue.

**Comment by bschmalhofer** [comment]
I noticed that there is still a `sleep 11;` in _scripts/test/Selenium/Customer/CustomerTicketOverview.t_ . This must be for reloading of a file _Kernel/Config/Files_ . But this should no longer be necessary. See 744c445a4bbacf0497f0cb8e3f3d9c9d1734c194 . Let's try it without the naps.
