### ISSUE TITLE
Test and fix OTOBO under Apache/mod_perl with mpm_prefork

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#1032]
There are some issues with running OTOBO 10.1.x under Apache/mod_perl. Note that this is the version with

```
        SetHandler perl-script
        PerlResponseHandler Plack::Handler::Apache2
        PerlSetVar psgi_app /opt/otobo/bin/psgi-bin/otobo.psgi

```
The scripts in bin/cgi-bin are not used there.

- [x] The `InterfaceInstaller->Content()` method should always return a string, not be printing to STDOUT
- [x] The `InterfaceMigrateFromOTRS->Content()`method should always return a string, not be printing to STDOUT
- [x] Explicitly returning "Status: 301 Moved Permanently\nLocation: https://$Host$RequestURI\n\n" is propably wrong, there is a ReDirect() method
- [x] Apache config files add an extra 'otobo/' in the path info
- [ ] Adding a DEFLATE filter should be investigated #1053
- [x] run installer.pl
- [ ] run migration.pl
- [ ] check the behaviour of public.pl
- [x] run the test suite successfully
- [ ] sanity test with HTTPS
- [x] Do not deactivate the MPMModel check #1063
- [x] SupportDataCollector tries to cache file handles #1062

**Comment by bschmalhofer** [comment]
Once this works with `PerlResponseHandler Plack::Handler::Apache2` we should check whether there are any problems with the wrapper script in _bin/cgi-bin_ .

**Comment by bschmalhofer** [comment]
Added Plack::Middleware::Deflater which seems to work fine. But I get an error for Firefox for the final page of installer.pl. Needs to be investigated.

**Comment by bschmalhofer** [comment]
installer.pl now works. The cause of the problem was that corrupt content was returned from Kernel::Modules::Installer::Run().

**Comment by bschmalhofer** [comment]
Remove the explicit emission of status code 301. But in order to be on the safe side, the setting _HTTPSForceRedirect_ should be tested separately.

**Comment by bschmalhofer** [comment]
Thinks look almost fine, after chosing the Apache worker module mpm_prefork instead mpm_event. Here are the remaining failures:

/opt/otobo/scripts/test/Console/Command/Maint/PostMaster/MailAccountFetch.t                               (Wstat: 256 Tests: 4 Failed: 1)
  Failed test:  4
  Non-zero exit status: 1
/opt/otobo/scripts/test/Selenium/Agent/AgentSplitSelectionACL.t                                           (Wstat: 512 Tests: 35 Failed: 2)
  Failed tests:  16, 25
  Non-zero exit status: 2
/opt/otobo/scripts/test/Selenium/Agent/AgentTicketActionCommonACL.t                                       (Wstat: 2560 Tests: 120 Failed: 10)
  Failed tests:  27, 32, 38, 50, 52, 54, 70, 85, 87, 99
  Non-zero exit status: 10
/opt/otobo/scripts/test/Selenium/Agent/MultiAttachmentUpload/CreateScreens.t                              (Wstat: 256 Tests: 38 Failed: 1)
  Failed test:  38
  Non-zero exit status: 1
/opt/otobo/scripts/test/SupportDataCollector.t                                                            (Wstat: 512 Tests: 242 Failed: 2)
  Failed tests:  239, 241
  Non-zero exit status: 2

**Comment by bschmalhofer** [comment]
The latest test run with rel-10_1 using OTOBO under Apache/mod_perl also hat Math::Random::Secure removed from Kernel::System::Main. `Math::Random::Secure::irand($Max)` is back to `int rand($Max)`. I think this is a good change, but it's definitely a different issue.

**Comment by bschmalhofer** [comment]
After reverting the irand change and after restarting from a clean slate we get:

```
/opt/otobo/scripts/test/Selenium/Agent/MultiAttachmentUpload/CreateScreens.t                              (Wstat: 256 Tests: 38 Failed: 1)
  Failed test:  38
  Non-zero exit status: 1
/opt/otobo/scripts/test/Selenium/Customer/MultiAttachmentUpload/TicketMessage.t                           (Wstat: 256 Tests: 18 Failed: 1)
  Failed test:  18
  Non-zero exit status: 1
/opt/otobo/scripts/test/SupportDataCollector.t                                                            (Wstat: 512 Tests: 242 Failed: 2)
  Failed tests:  239, 241
  Non-zero exit status: 2

```

**Comment by bschmalhofer** [comment]
Many failures in the latest run. Need to investigate what has been broken.

**Comment by bschmalhofer** [comment]
After fixing  RotherOSS/otobo-docker#58 we are back to three failures, but only _TicketMessage.t _ is in the intersection.

```
/opt/otobo/scripts/test/Selenium/Customer/CustomerTicketProcess.t                                         (Wstat: 768 Tests: 98 Failed: 3)
  Failed tests:  36, 44, 48
  TODO passed:   70-71
  Non-zero exit status: 3
/opt/otobo/scripts/test/Selenium/Customer/MultiAttachmentUpload/TicketMessage.t                           (Wstat: 256 Tests: 18 Failed: 1)
  Failed test:  18
  Non-zero exit status: 1
/opt/otobo/scripts/test/Selenium/Agent/AgentTicketSplitInlineImage.t                                      (Wstat: 256 Tests: 26 Failed: 1)
  Failed test:  26
  Non-zero exit status: 1

```

**Comment by bschmalhofer** [comment]
Lates test run showed only on failing script:

> /opt/otobo/scripts/test/Selenium/Customer/MultiAttachmentUpload/TicketMessage.t                           (Wstat: 256 Tests: 18 Failed: 1)
>   Failed test:  18
>   Non-zero exit status: 1
> 

Running that test by itself works most of the time. Let's dump the HTML with `$Selenium->get_page_source()`. Wenn the test succeeds we have the following HTML snippet:

>     <table class="Hidden Small DataTable AttachmentList" style="isplay: table;">
>         <tbody><tr class="Uploading">
>     <td class="Filetype ooo12g">
>         <i class="ooofo ooofo-text"></i>
>         <div class="ProgressContainer" style="width: 524px;">
>             
>         </div>
>     </td>
>     <td class="Filename ooo12g">Main-Test1.doc</td>
>     <td class="Filesize ooo12g" data-file-size="29184">28.5 KB</td>
>     <td class="Center">
>         <a href="#" class="AttachmentDelete ooo12g" tabindex="0" aria-label="Click to delete this attachment."><i class="ooofo ooofo-delete_outl"></i></a>
>     </td>
> </tr>
>         
>         </tbody>
>     </table>

In the error case the snippet looks similar:

>     <table class=\"Hidden Small DataTable AttachmentList\" style=\"display: table;\">
>         <tbody><tr class=\"Uploading\">
>     <td class=\"Filetype ooo12g\">
>         <i class=\"ooofo ooofo-text\"></i>
>         <div class=\"ProgressContainer\" style=\"width: 524px;\">
>             <span class=\"Progress\" style=\"overflow: hidden; width: 0.00154212%;\"></span>
>         </div>
>     </td>
>     <td class=\"Filename ooo12g\">Main-Test1.doc</td>
>     <td class=\"Filesize ooo12g\" data-file-size=\"29184\">28.5 KB</td>
>     <td class=\"Center\">
>         <a href=\"#\" class=\"AttachmentDelete ooo12g\" tabindex=\"0\" aria-label=\"Click to delete this attachment.\"><i class=\"ooofo ooofo-delete_outl\"></i></a>
>     </td>
> </tr>
>         
>         </tbody>
>     </table>
> 

The reported error is:

>   'Error while executing command: no such element: no such element: Unable to locate element: {"method":"xpath","selector":"(//a[@class=\'AttachmentDelete ooo12g\'])[1]"}
>   (Session info: chrome=90.0.4430.85) at /usr/local/share/perl/5.30.0/Selenium/Remote/Driver.pm line 411.
>  at /usr/local/share/perl/5.30.0/Selenium/Remote/Driver.pm line 361.

The difference in the HTML snippet is that the ProgressContainer is not empty. The assumption is that there is some JavaScript magic that shows the Attachment-Delete Link only when the upload is completed.

Let's handle this in a new issue.

**Comment by bschmalhofer** [comment]
Two failures now. _scripts/test/Selenium/Agent/Admin/AdminCustomerGroup.t_ is handled in #988 .

> /opt/otobo/scripts/test/Selenium/Agent/Admin/AdminCustomerGroup.t                                         (Wstat: 512 Tests: 38 Failed: 2)
>   Failed tests:  37-38
>   Non-zero exit status: 2
> /opt/otobo/scripts/test/SysConfig/RebuildConfigBug14910.t                                                 (Wstat: 256 Tests: 15 Failed: 1)
>   Failed test:  12
>   Non-zero exit status: 1

**Comment by bschmalhofer** [comment]
Could not reproduce the issue with _RebuildConfigBug14910.t_ . But added the case to #988 anyways. Closing this issue.

> bes:~/devel/OTOBO/otobo (rel-10_1)$ seq 30 | xargs -I{} prove -v -I . -I Kernel/cpan-lib/ scripts/test/SysConfig/RebuildConfigBug14910.t >> prove.out 2>&1
> bes:~/devel/OTOBO/otobo (rel-10_1)$ grep 'Result: ' prove.out | sort | uniq -c
>      30 Result: PASS
>

**Comment by bschmalhofer** [comment]
Reopening as there are still a few items on the TODO list.

**Comment by bschmalhofer** [comment]
Tests still look fine for the Plack::Handler::Apache2 case. The single failure ist likely only sporadic:

> /opt/otobo/scripts/test/Selenium/Agent/AgentTicketSplitInlineImage.t                                      (Wstat: 256 Tests: 26 Failed: 1)

**Comment by bschmalhofer** [comment]
Let's close this old issue as currently there are no known problems.
