### ISSUE TITLE
Support for Mysql 8 on Ubuntu 19.10

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#3]
Ubuntu 19.10 ships with MySQL 8.0.20.  MySQL 8.0 is the successor of MySQL 5.7. Looks like they dropped the 5 in order to confuse people. There are some changes in MySQL 8.0 that are relevant for OTOBO. See also https://dev.mysql.com/doc/refman/8.0/en/mysql-nutshell.html. 

The individual topics will be handled in dependent issues:

- [x] #4:  Creating users with GRANT no longer works. The default authentication plugin has changed from 'mysql_native_password' to 'caching_sha2_password'
- [x] #6: "groups" is now a reserved word and can no longer be used as an unquoted table name
- [x] #9: The query cache has been removed. Especially the variable  `query_cache_size` which is mentioned in the installation instructions
-  [x] The default character_set_server has changed from latin1 to utf8mb4. No action required here as the encoding **utf8** is explicitly stated in the CREATE TABLE statements
-  [x] The character set utf8mb3, which is aliased by utf8, is now deprecated, no action required for this issue. Switching to **utf8mb4** is not in the scope of this issue

**Comment by bschmalhofer** [comment]
OTOBO on MySQL 8 seems to work. Closing the issue.
