### ISSUE TITLE
Selenium Testing: reactivate TODO tests that are related to ACLs

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/otobo#763]
There is at least on test script that succeeds when run with a fresh database, but has a failure when running in the complete test suite. My hunch is that Event-handling might be messed up there. 
The plan is to mark these cases as TODO in #682 and fix them for this issue.
This effect might occur in several scripts.

TODO: fix TODO tests in 

- [ ] _scripts/test/Selenium/Agent/AgentSplitSelectionACL.t_
- [ ] _scripts/test/Selenium/Agent/AgentTicketActionCommonACL.t_
- [ ] _scripts/test/Selenium/Agent/AgentTicketBulkACL.t_

**Comment by bschmalhofer** [comment]
Tests are no longer set to TODO. Closing this issue.
